[package]
name = "hemi_typer"
version = "0.2.0"
authors = ["lectromoe <contact@lectro.moe>"]
edition = "2021"

[dependencies]
eframe = "0.16.0"
rand = "0.8.4"
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = []
persistence = ["eframe/persistence", "serde"]

[profile.release]
opt-level = 2