[package]
name = "HemiTyper"
version = "1.0.0"
authors = ["lectromoe <contact@lectro.moe>"]
edition = "2021"

[dependencies]
eframe = "0.16.0"
rand = "0.8.4"
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = []
persistence = ["eframe/persistence", "serde"]

[profile.release]
opt-level = 2

[patch.crates-io]

# eframe = { git = "https://github.com/emilk/egui", branch = "master" }
# eframe = { path = "../egui/eframe" }
