[package]
name = "hemi_typer"
version = "0.2.0"
authors = ["lectromoe <contact@lectro.moe>"]
edition = "2021"

[dependencies]
eframe = "0.18.0"
rand = "0.8.5"
serde = { version = "1.0.137", features = ["derive"], optional = true }
serde_json = "1.0.81"

[features]
default = []
persistence = ["eframe/persistence", "serde"]

[profile.release]
opt-level = 2