[application]

name = "hemi"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "HemiTyper"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = [
  "./style.css",
  "./tailwind.css"
]
script = []
custom = ["./CNAME"]

[web.resource.dev]
style = []
script = []

[[web.proxy]]
backend = "http://localhost:8000/api/"
