[application]
name = "hemi"
out_dir = "dist"
asset_dir = "assets"
default_platform = "web"

[web.app]
title = "HemiTyper"
base_path = "."


[web.watcher]
reload_html = true
watch_path = ["src", "assets", "./"]

[web.resource]
style = [
  "./style.css",
  "./tailwind.css"
]
script = []

[web.resource.dev]
style = []
script = []

[[web.proxy]]
backend = "http://localhost:8000/api/"

# [application.tools]
# tailwindcss = { config = "assets/tailwind.config.js" }
